/**
 * Element displaying a comment generated by the LLM.
 */
export class Comment extends HTMLElement {
    constructor (text: string) {
        super()
        this.classList.add('comment')
        this.text = text
    }

    set text (text: string) {
        this.innerText = text
    }
}
